### ISSUE TITLE
Gamemode Compatibility.?

### ISSUE THREAD

**Issue by The13thEmpire** [sisby-folk/switchy#60] opened 2023-10-19 21:48 UTC
Im not sure if there isn't gamemode swapping baked in or if its just a skill issue, but I can't seem to get my gamemode to change on a per preset basis.

Ver: 1.20.1
ModV: 2.8.4+1.20

**Comment by sisby-folk** [comment] 2023-10-20 00:31
duplicate of #8

**Closed as not planned by sisby-folk** 2023-10-20 00:31 UTC
