### ISSUE TITLE
[Suggestion] Add module for gamemode

### ISSUE THREAD

**Issue by Ultimushadow** [sisby-folk/switchy#56] opened 2023-09-21 10:45 UTC
One of the first things I thought would be useful with this mod is the ability to maintain the server I run without worrying about going into creative/spectator to fix something and accidentally deleting/adding items/xp from my survival character. I also thought about giving players a creative mode profile in a separate dimension, so they could test builds in the modpack without straining their pcs trying to run the thing themselves. It could also be interesting for sending players into adventure for a minigame or adventure map in the server. To my surprise though, it looks like gamemode is one of the only things not saved per profile, so I was hoping you would consider adding that feature in the future!

**Comment by sisby-folk** [comment] 2023-09-21 23:55
duplicate of #8 - gamemode switching should ideally be held within an addon to avoid messing with servers that don't want it

**Closed as not planned by sisby-folk** 2023-09-21 23:55 UTC

**Comment by Ultimushadow** [comment] 2023-09-22 00:10
Ah, my bad on the duplicate, it didn't come up when searching
I do think this would be very helpful, I hope an addon is in consideration!
